name: .NET MAUI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    env:
      Solution_Name: CardFramework.maui
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 11.0.x
        dotnet-quality: preview
        
    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore packages
      run: dotnet restore {{ env:Solution_Name }}.slnx

    - name: Build MAUI Libraries
      run: |
        dotnet build  ${{ env.Solution_Name }}/${{ env.Solution_Name }}.csproj -c $env:Configuration
      shell: pwsh

    - name: Pack Nuget Package
      run: |
        dotnet pack  ${{ env.Solution_Name }}/${{ env.Solution_Name }}.csproj
      shell: pwsh

    - name: Upload NUGET artifact
      uses: actions/upload-artifact@v4
      with:
        name: NUGET
        path: CardFramework.maui/bin/Release
        include-hidden-files: true
        if-no-files-found: error
